name: Build and Deploy React Vite App

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'
          cache: 'npm'

      - name: Install dependencies
        run: npm ci

      - name: Build React app
        run: npm run build

      - name: Deploy to GitHub Pages
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          branch: main# Deploy to the main branch
          folder: dist # Deploy the contents of the dist folder
          target-folder: dist # Deploy to the dist folder within main
          token: ${{ secrets.GITHUB_TOKEN }}